---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-demo
spec:
  selector:
    matchLabels:
      app: netology-demo
  template:
    metadata:
      labels:
        app: netology-demo
    spec:
      containers:
      - name: nginx-hugo
        image: {{ .Values.werf.image.demo }}